import { TBroker } from '@/modules/overview/types';
import { TTopic } from '@/modules/topics/types';

export const brokers: TBroker[] = [{
  id: 1,
  host: 'test_localhost',
  port: '8080',
  rack: '',
  controller: 'yes',
  partitions: '87',
},
{
  id: 2,
  host: 'test_google',
  port: '8080',
  rack: '',
  controller: 'no',
  partitions: '60',
}];

export const topics: TTopic[] = [
  {
    id: '1',
    name: 'StrikeSettleST',
    partitions: 14,
    preferred: 100,
    replicated: 0,
    config: false,
    size: 5,
    messages: 5,
  },
  {
    id: '2',
    name: 'StrikeSettleST2',
    partitions: 14,
    preferred: 100,
    replicated: 0,
    config: false,
    size: 5,
    messages: 5,
  },
  {
    id: '3',
    name: 'StrikeSettleST3',
    partitions: 14,
    preferred: 100,
    replicated: 0,
    config: false,
    size: 5,
    messages: 5,
  },
  {
    id: '13',
    name: 'StrikeSettleST13',
    partitions: 14,
    preferred: 100,
    replicated: 0,
    config: false,
    size: 5,
    messages: 5,
  },
  {
    id: '4',
    name: 'StrikeSettleST4',
    partitions: 14,
    preferred: 100,
    replicated: 0,
    config: false,
    size: 5,
    messages: 5,
  },
  {
    id: '5',
    name: 'StrikeSettleST5',
    partitions: 14,
    preferred: 100,
    replicated: 0,
    config: false,
    size: 5,
    messages: 5,
  },
]
